# Generated by Django 4.0.4 on 2022-05-23 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclo_phva', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestandar',
            name='permisos_usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='fk_item_estandar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ciclo_phva.itemestandar'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='permisos_usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estandar',
            name='fk_ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ciclo_phva.ciclo'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fk_registro_anual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciclo_phva.registroanual'),
        ),
    ]
