# Generated by Django 4.0.4 on 2022-06-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ambiental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenciagestionambiental',
            old_name='fk_item_estandar',
            new_name='fk_gestion_ambiental',
        ),
    ]
