# Generated by Django 4.0.4 on 2022-06-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ambiental', '0002_rename_fk_item_estandar_evidenciagestionambiental_fk_gestion_ambiental'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestionAmbiental',
            new_name='PoliticaGestionAmbiental',
        ),
    ]
