# Generated by Django 4.0.4 on 2022-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ambiental', '0003_rename_gestionambiental_politicagestionambiental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicagestionambiental',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
